"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
// Exercise the packaged positioning function with measured player/bar bounds.
const source = fs.readFileSync(process.env.JDVG_CONTENT_PATH || path.join(__dirname, "../content/content.js"), "utf8");
const start = source.indexOf("  function updateBarPosition(bar) {");
const end = source.indexOf("  function updateAllPositions()", start);
assert.ok(start >= 0 && end > start);
const state = { settings: { overlayPosition: "above-top-right" } };
const context = { currentState: state, shouldShowBar: () => true, document: { documentElement: { clientWidth: 1280 } } };
vm.createContext(context);
vm.runInContext(source.slice(start, end), context);
let rect = { top: 200, left: 100, right: 740 }, height = 31;
const bar = { host: { style: {} }, media: { getBoundingClientRect: () => rect }, wrap: { getBoundingClientRect: () => ({ height }) } };
const update = () => context.updateBarPosition(bar);
update();
assert.equal(Number.parseFloat(bar.host.style.top) + height, rect.top - 4, "bar stays entirely above video with a four-pixel gap");
assert.equal(bar.host.style.right, "548px");
height = 42;
update();
assert.equal(bar.host.style.top, "154px", "large bars remain above video");
state.settings.overlayPosition = "above-top-left";
update();
assert.equal(bar.host.style.left, "108px");
assert.equal(bar.host.style.right, "auto");
rect.top = 20;
update();
assert.equal(bar.host.style.top, "28px", "insufficient space falls back inside");
rect.top = 0;
update();
assert.equal(bar.host.style.top, "8px", "viewport-filling video keeps controls reachable");
rect.top = 300;
update();
assert.equal(bar.host.style.top, "254px", "scrolling restores outside placement when space returns");
state.settings.overlayPosition = "top-right";
update();
assert.equal(bar.host.style.top, "308px", "existing inside placement remains available");
context.shouldShowBar = () => false;
update();
assert.equal(bar.host.style.display, "none");
console.log("Overlay placement and viewport fallback tests passed");
